fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ajax_produits_options_by_type:
    path:     /ajax/commande/produits
    controller: App\Controller\CommandeController::produitsOptionsByTypeAction
    methods: [POST, GET]
    options:
        expose: true

ajax_type_by_product:
    path:     /ajax/typeByProduct
    controller: App\Controller\CommandeController::typeByProduitAction
    methods: [POST, GET]
    options:
        expose: true