fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ajax_produits_options_by_type:
    path:     /ajax/commande/produits
    controller: App\Controller\CommandeController::produitsOptionsByTypeAction
    methods: [POST, GET]
    options:
        expose: true

ajax_lignes_by_commande:
    path:     /ajax/lignes/commande
    controller: App\Controller\CommandeController::lignesByCommandeAction
    methods: [POST, GET]
    options:
        expose: true